name: Python CI with pytest

on:
  push:
    branches: all_Automation_Actions
  pull_request:
    branches: all_Automation_Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        cd /home/runner/work/all-learner-ai-app/all-learner-ai-app/allAutomation
        python -m pip install --upgrade pip
        pip install pytest==7.3.1
        pip install selenium==4.10.0
        pip install pytest-html==3.2.0
        pip install pytest-mock==3.11.1
        pip install webdriver-manager==3.8.6
        pip install selenium pytest gtts comtypes

      shell: /usr/bin/bash -e {0}
      env:
        pythonLocation: /opt/hostedtoolcache/Python/3.12.4/x64
        PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib/pkgconfig
        Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
        Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
        Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.12.4/x64
        LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.12.4/x64/lib

    - name: Run tests
      run: |
        cd /home/runner/work/all-learner-ai-app/all-learner-ai-app/allAutomation
        run: pytest my_project/tests/microphoneSimulationTest.py


# jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Install system dependencies
  #     run: sudo apt-get install -y portaudio19-dev
  #   - name: Set up Python
  #     uses: actions/setup-python@v2
  #     with:
  #       python-version: '3.12'
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install pytest==7.3.1
  #       pip install selenium==4.10.0
  #       pip install pytest-html==3.2.0
  #       pip install pytest-mock==3.11.1
  #       pip install webdriver-manager==3.8.6
  #       pip install pyaudio==0.2.13
  #   - name: Run tests
  #     run: pytest